trigger:
  branches:
    include:
      - master
      - releases/*
pr:
- '*'

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Compile pysys-vscode-extension"
    cd resources && git submodule init && git submodule update
    yarn --ignore-engines && yarn --ignore-engines pretest 
    echo ">>> Compiled pysys-vscode-extension"
  displayName: Build Extension
  env:
    DISPLAY: ':99.0'